version: '3'

services:

  postgres:
    image: postgres
    volumes:
      - postgres.data:/var/lib/postgresql/data

  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres

volumes:
  postgres.data:
