# Generated by Django 2.0.2 on 2018-02-16 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_text',
            field=models.CharField(default='default', max_length=200),
            preserve_default=False,
        ),
    ]
